# Generated by Django 5.1.2 on 2024-10-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vegetableprice',
            old_name='price',
            new_name='max_price',
        ),
        migrations.RemoveField(
            model_name='vegetableprice',
            name='unit',
        ),
        migrations.AddField(
            model_name='vegetableprice',
            name='min_price',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
