# Generated by Django 5.1.2 on 2024-10-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_rename_price_vegetableprice_max_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetableprice',
            name='avg_price',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
